#      _         _            _      ___   __  __ 
#  _  | |  ___  (_)  _ _     /_\    / __| |  \/  |
#  | || | / _ \ | | | ' \   / _ \  | (__  | |\/| |
#   \__/  \___/ |_| |_||_| /_/ \_\  \___| |_|  |_|
#           by fernanACM
#Here is the page for you to choose the sound you like: https://www.digminecraft.com/lists/sound_list_pe.php
#Remember that the type of music must be of the " ", 
#I show you an example.
#PlaySoundJoin: "random.pop"
#===========================================
           #SOUNDS
#Sound when it enters the server
PlaySoundJoin: "mob.irongolem.hit"
#Sound when you exit the server.
PlaySoundQuit: "mob.irongolem.walk"
#JoinACM button sound
PlaySoundButton: "random.fizz"                                               
#============================================
          #TITLES - MESSAGES
#Message chat: Use '\n' to go down in the text
Join-Message: "§aWolcome bro :)"
#Welcome title
Join-Title: "§l§5Wolcome"
#welcome subtitle
Join-SubTitle: "§rThanks for using JoinACM"
#============================================
          #FORM
#JoinACM Title
JoinUI-Title: "§l§5JoinACM"
#JoinACM Content: Use '\n' to go down in the text
JoinUI-Content: "§eWelcome to the server friend :D\n§e I hope you like it very much."
#JoinACm Button
JoinUI-Button: "Click to continue"
#============================================
